# Generated by Django 5.1.2 on 2024-11-15 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userform',
            name='account_number',
            field=models.CharField(default=0, editable=False, max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='userform',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userform',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
