# Generated by Django 5.1.2 on 2024-11-16 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_userform_account_number_alter_userform_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='account_number',
        ),
    ]
